### ISSUE TITLE
update CSS for button accessibilitiy

### ISSUE THREAD

**Issue by 7mary4** [teachaccess/tutorial#27]
### Color contrast
Buttons and links use a blue with #2199e8, which is only 3.09:1
Replace this with #1b78ce for 4.57:1 contrast

```
.button {
 display:inline-block;
 text-align:center;
 line-height:1;
 cursor:pointer;
 -webkit-appearance:none;
 -webkit-transition:background-color .25s ease-out,color .25s ease-out;
 transition:background-color .25s ease-out,color .25s ease-out;
 vertical-align:middle;
 border:1px solid transparent;
 border-radius:0;
 padding:.85em 1em;
 margin:0 0 1rem;
 font-size:.9rem;
 background-color:#1b78ce;
 color:#fefefe
}
```

### Hover and Focus Style
The current buttons have minimal focus/hover styles. This update adds a border. 
```
.button:focus, .button:hover {
    background-color: #1583cc;
    color: #fefefe;
    outline: 1px solid #1583cc;
    outline-offset: 2px;
}
```

<img width="183" alt="button with new focus style" src="https://user-images.githubusercontent.com/459953/137416473-a394d10c-88d7-4d20-9be2-44c030b217a3.png">

file: 
https://github.com/teachaccess/tutorial/blob/master/docs/style.css

**Comment by pedaars** [comment]
I can look at this

**Comment by rachelruderman** [comment]
@7mary4 Any issues that are not content related I'm going to temporarily close until we've migrated from exerslide to Docusaurus
