### ISSUE TITLE
Automate deploy process

### ISSUE THREAD

**Issue by rachelruderman** [teachaccess/tutorial#31]
**Current deploy process:**
1. User makes changes
2. `exerslide serve` to generate `docs/` files
3. PR merged

**Desired deploy process:**
1. User makes changes
2. PR merged
3. GitHub actions runs `exerslide serve` to generate `docs/` files

**Comment by rachelruderman** [comment]
> @rachelruderman a workflow can be made that runs exerslide serve , so do you want to trigger that workflow when a PR is merged or do you want to automate the process of merging PR too?

Thank you @pururaj987 ! When you say "automate the process of merging PR", are you referring to a separate PR with the autogenerated docs? If so, yes!

1. Author makes

**Comment by pururaj987** [comment]
Ok , so you mean whenever anyone makes some changes and pushes it to any branch , docs should be generated and a PR should be automatically generated?

**Comment by rachelruderman** [comment]
Closing for now since this depends on https://github.com/teachaccess/tutorial/issues/32

**Comment by rachelruderman** [comment]
Closing because altho local development is fixed now, we'll be migrating soon to Docusaurus since exerslide has been archived for 5 years. Deployment should be automated after hte move to docusaurus
