### ISSUE TITLE
Color contrast issues on Pagination

### ISSUE THREAD

**Issue by 7mary4** [teachaccess/tutorial#34]
Currently, the page x/y span is #888
This should at least be #757575. It's secondary, but important information. So it could also be #666.
I would suggest #666. 
![image](https://user-images.githubusercontent.com/459953/137642229-92557a80-2a24-4562-8e19-140b6c4367d9.png)

This is located on line 10 of tutorial/css/taop.css

```
.exerslide-toolbar-text,
.exerslide-toolbar-button {
  color: #888;
}
```

becomes

```
.exerslide-toolbar-text,
.exerslide-toolbar-button {
  color: #666;
}
```

### Hover style
When shifting the default text to a darker grey, the :hover style is minimal. 
it shifts from #666 to #555

When color is the only indication of hover (or focus), we need a 3:1 contrast between the default and hover color. This can be achieved by using #1c1c1c as the hover color
![image](https://user-images.githubusercontent.com/459953/137642348-83209070-2abd-4e2a-b59e-df17caafb9e7.png)

This is located on line 29 of tutorial/js/components/css/toolbar.css
```
.exerslide-toolbar-button:focus,
.exerslide-toolbar-button:hover {
  color: #555;
}
```
this would become
```
.exerslide-toolbar-button:focus,
.exerslide-toolbar-button:hover {
  color: #1c1c1c;
}

```

**Comment by jpacsai** [comment]
hi, can I work on this issue? please assign me :)

**Comment by rachelruderman** [comment]
@7mary4 Any issues that are not content related I'm going to temporarily close until we've migrated from [exerslide](https://github.com/facebookarchive/exerslide) to [Docusaurus](https://github.com/facebook/docusaurus/)
