### ISSUE TITLE
Table of Contents - Color Contrast 

### ISSUE THREAD

**Issue by 7mary4** [teachaccess/tutorial#35]
The current left nav uses Black text on a grey background for the menu items. The selected and hover styles are a light blue. Also, there's a chevron button for collapsing the menu that is light grey on grey. This issue is to update the styles to improve contrast and interactive styles. 

### Menu button
![image](https://user-images.githubusercontent.com/459953/137642708-4555db5d-bc62-47ef-9d38-edc59d978474.png)
line 52 of tutorial/js/components/css/toc.cess

```
.exerslide-toc-toggleButton {
  align-self: flex-end;
  background-color: transparent;
  border: none;
  color: #AAA;
  cursor: pointer;
  flex-shrink: 0;
  font-size: 1em;
  outline-width: thin;
  padding: 0.5em;
}
```

This becomes
![image](https://user-images.githubusercontent.com/459953/137642816-036c546b-4a58-489d-b27b-61e6b6543033.png)

```
.exerslide-toc-toggleButton {
  align-self: flex-end;
  background-color: transparent;
  border: none;
  color: #666;
  cursor: pointer;
  flex-shrink: 0;
  font-size: 1em;
  outline-width: thin;
  padding: 0.5em;
}
```

The hover style inherits the #333 from the body. No change is needed for :focus.

### Table of content elements

These currently use a light blue on grey to show :hover and selected state. 
We can make these much more readable and distinct by making the blue darker and adding a white background. 

![image](https://user-images.githubusercontent.com/459953/137642904-a0e3aa28-acb6-4ed2-a9b3-2344a4e721e0.png)

This is at line 111 of the same CSS file

#### Current
```
.exerslide-toc-entry.active,
.exerslide-toc-entry.active > a,
.exerslide-toc-entry:hover {
  color: #428bca;
}
```

#### Updated
```
.exerslide-toc-entry.active,
.exerslide-toc-entry.active > a,
.exerslide-toc-entry:hover {
  color: #347bb8;
  background:#ffffff;
}
```

**Comment by rachelruderman** [comment]
@7mary4 Any issues that are not content related I'm going to temporarily close until we've migrated from exerslide to Docusaurus
