### ISSUE TITLE
Color contrast: update link color to provide 4.5:1

### ISSUE THREAD

**Issue by 7mary4** [teachaccess/tutorial#37]
The current experience uses #2199e8 for links. this only provides 3.09:1 Color contrast. 
![Links within page that have inadequate color contrast](https://user-images.githubusercontent.com/459953/137644152-b299a378-a4c2-4080-89ec-4ccb060dcd51.png)

We can use the same blue suggested for the left column to make links in the body accessible. 
#337ab6
However, links that depend solely on color must have 3:1 contrast between the link and surrounding text. This can be solved by adding an underline to links within the main section 

This is inheriting styles from the normalize.css file. So it would be best to override in the  tutorial/css/style.css  file. Perhaps after line 169
We can target the main section links with [role="main] a {...}

```
[role="main"] a {
color: #337ab6;
text-decoration:underline;
}

[role="main"] a:hover, [role="main"] a:focus {
color: #1585cf;
text-decoration:none;
}
```
![updated links with darker blue and underline. hover style has no underline](https://user-images.githubusercontent.com/459953/137644974-4225c41d-568b-4bda-bcb5-d8a3468e2196.png)

**Comment by rachelruderman** [comment]
@7mary4 Any issues that are not content related I'm going to temporarily close until we've migrated from exerslide to Docusaurus
