### ISSUE TITLE
Add live code exercises: code/menus.mdx

### ISSUE THREAD

**Issue by rachelruderman** [teachaccess/tutorial#55]
## What's the problem?
The tutorial's underlying framework, [exerslide](https://github.com/facebookarchive/exerslide), was archived by its owner and has not been updated for several years. We want to modernize by migrating the tutorial to [docusaurus](https://github.com/facebook/docusaurus/)

## How can you help?
Recreate the live code exercises for the [Menus section](https://teachaccess.github.io/tutorial/#/10)

## How to do it?
Please see this [step-by-step guide](https://github.com/teachaccess/tutorial/blob/docusaurus/migration-instructions.md) for how to complete this task

Check out the Headings slide for an example ([before](https://github.com/teachaccess/tutorial/blob/master/slides/02-Developers/01-headings.html.md) and [after](https://github.com/teachaccess/tutorial/blob/docusaurus/docs/code/headings.mdx))

## Helpful links
- [Tutorial website](https://teachaccess.github.io/tutorial/#/10)
- [Exerslide file (old)](https://github.com/teachaccess/tutorial/blob/master/slides/02-Developers/08-menu.html.md)
- [Docusaurus file (new)](https://github.com/teachaccess/tutorial/blob/docusaurus/docs/code/menus.mdx)

**Comment by amkonstant** [comment]
> @rachelruderman I might be missing something, but I was wondering how the `js/scriptHelper.js` should be migrated. Should I just copy the file and load it or you have something else in mind?

Nevermind, the last push for `dialogs` cleared things for me :)

**Comment by rachelruderman** [comment]
Hi @amkonstant , glad that helped! The dialogs implementation isn't complete -- scripthelper.js serves to abstract some of the functionality that isn't needed in the live code examples. That's the ideal state we want to be in. You can look at the PR for dialogs to see the conversation i had with the developer around it

If abstracting it is too complicated for this issue i can create a separate issue for that, let me know what you'd like to do
