### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jshwlkr** [teachaccess/tutorial#6]
How is the content licensed (and could you be more explicit about it)?

**Comment by nfreear** [comment]
Hi,

I'm interested in the content, and possible re-use.

As @jshwlkr requests, please can you explicitly license the repository, using a `LICENSE.txt` file and/or the `license` field in `package.json`:

 * https://help.github.com/articles/licensing-a-repository/
 * https://docs.npmjs.com/files/package.json#license

Adding a license may encourage forking and contributions.

Also, 👍  for #5.

Thanks,

Nick
