### ISSUE TITLE
Add numbers to navigation bar

### ISSUE THREAD

**Issue by rachelruderman** [teachaccess/tutorial#76]
**Expected behavior:** Navigation bar has numbers, but the title in the content section does not. I.e.:

![Screen Shot 2021-10-30 at 11 31 13 AM](https://user-images.githubusercontent.com/26726429/139554305-564e2b54-4472-4f37-80ab-8ca01943727b.png)

**Comment by slashgk** [comment]
Hi @rachelruderman 
Do we want numbers on the titles as well?
For example, the title should be `1.1 Using this Tutorial`

**Comment by rachelruderman** [comment]
Hi @slashgk! We want the navigation bar to have the numbers, but no number in the content section (see the screenshot  in issue description for reference)

For example, the nav bar should be `1.1 Using this tutorial`, but the title should be `Using this tutorial`

**Comment by slashgk** [comment]
But we already have numbers in the navigation bar if I am not wrong.

**Comment by rachelruderman** [comment]
This is for the docusaurus branch, sorry i didn't make that clear!
