### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by AEDesigns** [teachaccess/tutorial#95]
# Expected Behavior

Please describe the behavior you are expecting

The page to load when running the serve command

What is the current behavior?

It is stuck on the spinning gear screen on localhost:8080 after running the serve command.

## Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Fork the repo
2. Clone the repo
3. run npm i
4. run exerslide serve
5. Stuck on the gear spinning screen

**Comment by AEDesigns** [comment]
A screen shot of the error I'm getting in the console
![image](https://user-images.githubusercontent.com/43253284/148285915-61eac33c-be71-422f-8b0c-69e097b48872.png)

**Comment by rachelruderman** [comment]
Hi @AEDesigns ! Sorry for the delay, just saw your issue now. The old `exerslide` framework has been archived so we're migrating to docusaurus. Can you try again using the `docusaurus` branch in this repo?
1. `git checkout docusaurus`
1. `nvm use`
1. `cd website`
1. `yarn install`
1. `yarn start`
