### ISSUE TITLE
In line Link color and contrast

### ISSUE THREAD

**Issue by jenniferh2** [teachaccess/tutorial#99]
# Expected Behavior

I should be able to detect a link inline with black text. It is very difficult to do so.

# Current Behavior

Links appear in a light purple. The contrast ratio is very close 4.1:1 Red weak and blue weak color blindness makes it harder to see. 

## Steps to reproduce

Please provide detailed steps for reproducing the issue.

1. Import a screenshot of the purple text into color.adobe.com color analyzer to see the contrast ratio
2. In developer tools run Chrome Lens to see the impact of color blindness

Recommend:
If you stay with purple:  text #5900B4 (Eggplant 100) / Background #FFFFFF (Pepper 0)

**Comment by rachelruderman** [comment]
Thank you Jennifer!! Does the recommendation fix the issue during hover state as well?

**Comment by jenniferh2** [comment]
What I have seen work well in Lumapps is using bold in a hover state.

**Comment by 7mary4** [comment]
Underlines are better for inline links

**Comment by 7mary4** [comment]
With inline links that lack text decoration, there needs to be 3:1 contrast between link and surrounding text

**Comment by 7mary4** [comment]
Here's a style we could add to the basic css or create an inline link variable. 
p a {text-decoration: underline;}
p a:hover {text-decoration: none;}

**Comment by 7mary4** [comment]
add focus
p a {text-decoration: underline;}
p a:hover, p a:focus {text-decoration: none;}
